// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxqiuuP21E_kiRNMOU9exidltrF7V6BaA',
    appId: '1:488717454819:web:7b1ccd99a6ce7e9ab164d6',
    messagingSenderId: '488717454819',
    projectId: 'bible-compass',
    authDomain: 'bible-compass.firebaseapp.com',
    storageBucket: 'bible-compass.appspot.com',
    measurementId: 'G-N34VG7JK2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkAJ8ODyDhMq5YPPEX664gwWtE2Z0JgpM',
    appId: '1:488717454819:android:c130e0893e75c3a6b164d6',
    messagingSenderId: '488717454819',
    projectId: 'bible-compass',
    storageBucket: 'bible-compass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVcZj_N9IcoRVKtGhBDDWEId0dl3Qz6wQ',
    appId: '1:488717454819:ios:cf051361b9514529b164d6',
    messagingSenderId: '488717454819',
    projectId: 'bible-compass',
    storageBucket: 'bible-compass.appspot.com',
    iosClientId: '488717454819-bg8ag96nioq98q968n440qrgkv8s3n3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.bibleCompassApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVcZj_N9IcoRVKtGhBDDWEId0dl3Qz6wQ',
    appId: '1:488717454819:ios:2e9b303ff69d7a2fb164d6',
    messagingSenderId: '488717454819',
    projectId: 'bible-compass',
    storageBucket: 'bible-compass.appspot.com',
    iosClientId: '488717454819-6nuhrv7hq9e06ft3rdq3ce37f670npmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.bibleCompassApp.RunnerTests',
  );
}
